# Generated by Django 3.2.7 on 2021-09-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
    ]
